# Generated by Django 5.0 on 2024-04-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0001_initial"),
        ("users", "0002_user_first_name_user_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="images",
            field=models.ManyToManyField(related_name="users", to="images.images"),
        ),
    ]
