# Generated by Django 5.0 on 2023-12-21 07:37

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Transports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('BUS', 'Avtobus'), ('METRO', 'Metro'), ('MARSHUTKA', 'Marshutka')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('partnership', models.BooleanField(default=False)),
                ('need_people_count', models.IntegerField(default=0)),
                ('room_count', models.IntegerField(default=1)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('location_x', models.CharField(blank=True, max_length=255, null=True)),
                ('location_y', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('UZS', 'So`m')], default='UZS', max_length=10)),
                ('total_price', models.FloatField(blank=True, null=True)),
                ('price_for_one', models.FloatField(blank=True, null=True)),
                ('appartment_status', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('description', models.TextField(blank=True, null=True)),
                ('conditioner', models.BooleanField(default=False)),
                ('washing_machine', models.BooleanField(default=False)),
                ('images', models.ManyToManyField(related_name='announcement', to='images.images')),
            ],
        ),
    ]
