# Generated by Django 5.0 on 2024-04-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("announcement", "0003_transports_ri"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="fridge",
            field=models.BooleanField(default=False),
        ),
    ]
