# Generated by Django 5.0 on 2023-12-21 07:37

import images.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('image', models.ImageField(upload_to=images.models.image_upload_path)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
